# Generated by Django 5.0.4 on 2024-05-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0002_rename_gpt_response_chatmessage_gptbaseresponse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='created_at',
            new_name='createdDate',
        ),
    ]
